//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int Cityid { get; set; }
        public string Cityname { get; set; }
        public Nullable<int> SId { get; set; }
    
        public virtual state state { get; set; }
    }
}
