//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_tbl
    {
        public Department_tbl()
        {
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int DeptID { get; set; }
        public string Dept_Name { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
